/* Simulation.
 *
 * Test infrastructure, not a demo. The engine is quiet most of the time — a
 * critical convergence may not arrive for hours — so a director that only ever
 * sees a calm world cannot be developed or checked. This injects controlled
 * events so the takeover, the transitions and the priority grading can be
 * exercised on demand.
 *
 * It is loaded only when the page is opened with `?sim=1`, and it writes to its
 * own channel. It never touches the store's data, so a simulated event can
 * never be mistaken for a real reading, and a screen left open in production
 * never sees one. */

import { grade } from "../studio/priority.js";

const SIM_QUIET = 8_000;

export function runSimulation({ studio, store, breaking }) {
  const scenarios = {
    /** A calm signal: graded but not interrupting. */
    signal(priority = "MEDIUM") {
      const signal = fakeSignal({ sigma: priority === "MEDIUM" ? 3.6 : 1.4 });
      store.bus.emit("sse:signal", signal);
      return signal;
    },
    /** A loud anomaly: should transition, and at CRITICAL should take over. */
    breaking(priority = "CRITICAL") {
      const sigma = priority === "CRITICAL" ? 9.4 : 5.6;
      const signal = fakeSignal({ sigma });
      studio.director.setEnabled(true);
      store.bus.emit("sse:signal", signal);
      if (priority === "CRITICAL") studio.startTakeover(signal, grade(signal), { action: "takeover" });
      return signal;
    },
    /** Two independent sources on the same change. */
    convergence() {
      const signal = fakeSignal({ sigma: 6.2, types: ["CONVERGENCE", "ANOMALY", "IMPACT"] });
      studio.director.setEnabled(true);
      store.bus.emit("sse:signal", signal);
      return signal;
    },
    /** A collector dying — the case that must never read as a quiet world. */
    sourceFailure(id = "usgs_earthquakes") {
      store.bus.emit("sse:source_failed", { source_id: id });
    },
    resolved() {
      const signal = fakeSignal({ sigma: 2.1, status: "RESOLVED" });
      store.bus.emit("sse:signal", signal);
      return signal;
    },
    scene(id = "map") {
      studio.cutTo(id, { reason: "sim" });
    },
  };

  // A short cycle so the shell can be watched without waiting. It stops as soon
  // as the tab is hidden, so a forgotten simulation does not run forever.
  let timer = null;
  let step = 0;
  const cycle = ["signal", "scene", "convergence", "resolved", "sourceFailure", "breaking"];
  const tick = () => {
    const name = cycle[step % cycle.length];
    step += 1;
    try { scenarios[name]?.(); } catch (err) { console.error("[sim]", name, err); }
  };

  const start = () => {
    if (timer) return;
    tick();
    timer = setInterval(tick, SIM_QUIET);
  };
  const stop = () => { if (timer) clearInterval(timer); timer = null; };

  document.addEventListener("visibilitychange", () => {
    if (document.hidden) stop(); else start();
  });
  start();

  // Reachable from the console as `wse.sim.breaking("CRITICAL")`.
  window.wse.sim = { ...scenarios, start, stop, next: tick };
  console.info("[sim] simulation active — ?sim=1. Events are synthetic and are not stored.");
}

function fakeSignal({ sigma = 3.5, types = ["ANOMALY"], status = "CONFIRMED" } = {}) {
  const now = new Date();
  const first = new Date(now.getTime() - 42 * 60 * 1000);
  return {
    id: `sim_${Math.random().toString(36).slice(2, 10)}`,
    event_id: `evt_sim_${Math.random().toString(36).slice(2, 8)}`,
    types,
    title: "Simulated change for broadcast testing",
    summary: `synthetic observation(s); largest deviation ${sigma.toFixed(1)}σ; sustained 42 min`,
    first_seen: first.toISOString(),
    last_updated: now.toISOString(),
    duration_seconds: 42 * 60,
    confidence: 0.71,
    evidence: [
      { observation_id: "obs_sim_1", source_id: "sim_source", observed_at: now.toISOString(), statement: `simulated reading (+${sigma.toFixed(1)}σ)` },
      { observation_id: "obs_sim_2", source_id: "sim_source", observed_at: now.toISOString(), statement: `simulated reading (+${(sigma * 0.8).toFixed(1)}σ)` },
    ],
    entities: ["sim_entity"],
    categories: ["sim"],
    location: null,
    lens_matches: [],
    quality: { deviation_sigma: sigma },
    direction: "up",
    reasons: ["synthetic event injected by ?sim=1"],
    series_key: "sim_source::sim_entity::sim_metric::unit",
    status,
    data_origin: "SYNTHETIC",
    narrative: "This signal was generated by the simulation layer for development.",
    _simulated: true,
  };
}
